# Generated by Django 5.2.7 on 2026-02-03 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('target', models.TextField(verbose_name='Objetivo')),
                ('opening_date', models.DateField(verbose_name='Data de Abertura')),
                ('closing_date', models.DateField(verbose_name='Data de Fechamento')),
                ('file', models.FileField(blank=True, null=True, upload_to='proposals/retifications/', verbose_name='Arquivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('target', models.TextField(blank=True, null=True, verbose_name='Objetivo')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='Data de Abertura')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('proposal_file', models.FileField(blank=True, null=True, upload_to='proposals/', verbose_name='Arquivo')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_proposals', to='institution.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
