# Generated by Django 5.2.7 on 2025-11-17 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proprsal_file',
            field=models.FileField(blank=True, null=True, upload_to='institutions/'),
        ),
        migrations.CreateModel(
            name='RectifyProposal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('departament', models.CharField(max_length=100)),
                ('rectify_file', models.FileField(blank=True, null=True, upload_to='institutions/')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectifications', to='proposals.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
