# Generated by Django 5.2.7 on 2026-02-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='number_of_places',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Vagas'),
        ),
    ]
