# Generated by Django 5.2.7 on 2026-02-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='proposals/retifications/', verbose_name='Arquivo'),
        ),
    ]
