# Generated by Django 5.2.7 on 2026-01-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institution_city_institution_cnpj_and_more'),
        ('pesquisador', '0001_initial'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RectifyProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('target', models.TextField(verbose_name='Objetivo')),
                ('opening_date', models.DateField(verbose_name='Data de Abertura')),
                ('closing_date', models.DateField(verbose_name='Data de Fechamento')),
                ('rectify_file', models.FileField(blank=True, null=True, upload_to='proposals/', verbose_name='Arquivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='departament',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='proprsal_file',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='proposal',
            name='closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_proposals', to='institution.institution'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='opening_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Abertura'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_file',
            field=models.FileField(blank=True, null=True, upload_to='proposals/', verbose_name='Arquivo'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='research',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='researcher_proposals', to='pesquisador.researcher'),
            preserve_default=False,
        ),
    ]
