# Generated by Django 5.2.7 on 2026-01-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institution_city_institution_cnpj_and_more'),
        ('pesquisador', '0001_initial'),
        ('proposals', '0002_rectifyproposal_remove_proposal_departament_and_more'),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='submissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='submission.submission'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='target',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='rectifyproposal',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectify_institution_proposals', to='institution.institution'),
        ),
        migrations.AddField(
            model_name='rectifyproposal',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectify_researcher_proposals', to='pesquisador.researcher'),
        ),
    ]
