# Generated by Django 5.2.7 on 2026-01-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposal_submissions_proposal_target_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='research',
            new_name='researcher',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='research',
            new_name='researcher',
        ),
    ]
