# Generated by Django 5.2.7 on 2026-01-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_rename_research_proposal_researcher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='rectify_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='submissions',
        ),
        migrations.RemoveField(
            model_name='version',
            name='closing_date',
        ),
        migrations.RemoveField(
            model_name='version',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='version',
            name='opening_date',
        ),
        migrations.RemoveField(
            model_name='version',
            name='researcher',
        ),
    ]
