# Generated by Django 5.2.7 on 2026-01-13 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisador', '0001_initial'),
        ('proposals', '0004_rename_research_proposal_researcher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researcher_proposals', to='pesquisador.researcher'),
        ),
    ]
