# Generated by Django 5.2.7 on 2026-01-14 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_alter_proposal_researcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='submissions',
        ),
        migrations.RemoveField(
            model_name='version',
            name='researcher',
        ),
    ]
