# Generated by Django 5.2.7 on 2026-01-05 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('institution', '0002_institution_city_institution_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='city',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='state',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='street',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='address.address'),
        ),
    ]
