# Generated by Django 5.2.7 on 2026-02-03 17:41

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Formatos: JPG, JPEG, PNG, GIF, WEBP, BMP. Tamanho máximo: 5MB.', null=True, upload_to=user.models.UploadToPath('profile_pictures'), validators=[user.models.validate_image_extension, user.models.validate_image_size], verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
