# Generated by Django 5.2.7 on 2026-02-03 22:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_scientific_relevance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota de Relevância Científica')),
                ('note_feasibility_methodological', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota de Viabilidade Metodológica')),
                ('note_expected_results', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota de Resultados Esperados')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Pontuação Total')),
                ('project_report', models.TextField(blank=True, null=True, verbose_name='Relatório do Projeto')),
                ('strength_points', models.TextField(blank=True, null=True, verbose_name='Pontos Fortes')),
                ('weak_points', models.TextField(blank=True, null=True, verbose_name='Pontos Fracos')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Recomendações')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('completed', 'Concluída')], default='pending', max_length=20, verbose_name='Status da Avaliação')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('expertise', models.CharField(max_length=200, verbose_name='Área de Atuação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avaliador',
                'verbose_name_plural': 'Avaliadores',
            },
        ),
        migrations.CreateModel(
            name='ReviewerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail do Convidado')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Atribuição')),
                ('notified', models.BooleanField(default=False, verbose_name='Avaliador Notificado?')),
                ('notified_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Notificação')),
            ],
            options={
                'verbose_name': 'Atribuição de Avaliação',
                'verbose_name_plural': 'Atribuições de Avaliações',
            },
        ),
    ]
