# Generated by Django 5.2.7 on 2026-01-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_scientific_relevance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota de Relevância Científica')),
                ('note_feasibility_methodological', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota de Viabilidade Metodológica')),
                ('note_expected_results', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota de Resultados Esperados')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pontuação Total')),
                ('project_report', models.TextField(verbose_name='Relatório do Projeto')),
                ('strength_points', models.TextField(verbose_name='Pontos Fortes')),
                ('weak_points', models.TextField(verbose_name='Pontos Fracos')),
                ('recommendations', models.TextField(verbose_name='Recomendações')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('expertise', models.CharField(max_length=200, verbose_name='Área de Atuação')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
