# Generated by Django 5.2.7 on 2026-01-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_evaluations', to='proposals.proposal'),
        ),
    ]
