# Generated by Django 5.2.7 on 2026-02-03 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0003_initial'),
        ('submission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.reviewer', verbose_name='Avaliador'),
        ),
        migrations.AddField(
            model_name='submissionassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído por'),
        ),
        migrations.AddField(
            model_name='submissionassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='evaluations.reviewer', verbose_name='Avaliador'),
        ),
        migrations.AddField(
            model_name='submissionassignment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='submission.submission', verbose_name='Submissão'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='evaluations.submissionassignment', verbose_name='Atribuição'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionassignment',
            unique_together={('submission', 'reviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('submission', 'reviewer')},
        ),
    ]
