# Generated by Django 5.2.7 on 2026-01-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_remove_institution_city_and_more'),
        ('pesquisador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('weekly_workload', models.IntegerField(verbose_name='Carga Horaria')),
                ('start_date', models.DateField(verbose_name='Data de Inicio')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
                ('total_workload', models.IntegerField(verbose_name='Carga Horaria Total')),
                ('thematic_axis', models.CharField(max_length=255, verbose_name='Eixo Tematico')),
                ('interdisciplinary_project', models.BooleanField(verbose_name='Projeto Interdisciplinar')),
                ('disciplines', models.CharField(max_length=255, verbose_name='Disciplinas')),
                ('courses', models.CharField(max_length=255, verbose_name='Cursos')),
                ('project_file', models.FileField(blank=True, null=True, upload_to='projects/', verbose_name='Arquivo')),
                ('Institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto_campus', to='institution.institution')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_researcher', to='pesquisador.researcher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
