# Generated by Django 5.2.7 on 2026-01-26 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisador', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.CharField(choices=[('Matematica', 'Matemática'), ('Fisica', 'Física'), ('Quimica', 'Química'), ('Biologia', 'Biologia'), ('Engenharia', 'Engenharia')], default='Matematica', max_length=50, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='project',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_researcher', to='pesquisador.researcher', verbose_name='Pesquisador'),
        ),
    ]
