# Generated by Django 5.2.7 on 2026-01-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_remove_evaluation_institution_and_more'),
        ('pesquisador', '0002_remove_researcher_user'),
        ('proposals', '0005_rename_rectify_file_version_file_and_more'),
        ('submission', '0003_rename_rectify_file_version_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Researcher',
        ),
    ]
