# Generated by Django 5.2.7 on 2026-01-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisador', '0003_project_course_alter_project_researcher'),
        ('proposals', '0006_remove_proposal_researcher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_projects', to='proposals.proposal', verbose_name='Edital'),
        ),
    ]
