# Generated by Django 5.2.7 on 2026-01-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisador', '0004_project_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='proposal',
        ),
    ]
