# Generated by Django 5.2.7 on 2026-01-26 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisador', '0005_remove_project_proposal'),
        ('proposals', '0006_remove_proposal_researcher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='proposals.proposal', verbose_name='Edital'),
        ),
    ]
