# Generated by Django 5.2.7 on 2026-01-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título da Retificação')),
                ('abstract', models.TextField(verbose_name='Resumo')),
                ('keywords', models.CharField(max_length=255, verbose_name='Palavras-chave')),
                ('justification', models.TextField(verbose_name='Justificativa')),
                ('methodology', models.TextField(verbose_name='Metodologia')),
                ('project_timeline', models.TextField(verbose_name='Cronograma do Projeto')),
                ('project_budget', models.TextField(verbose_name='Orçamento do Projeto')),
                ('expected_results', models.TextField(verbose_name='Resultados Esperados')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/rectifications/', verbose_name='Arquivo da Retificação')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título da Retificação')),
                ('status', models.CharField(max_length=50, verbose_name='Status da Submissão')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_list', to='proposals.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
