# Generated by Django 5.2.7 on 2026-01-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('pesquisador', '0001_initial'),
        ('proposals', '0002_rectifyproposal_remove_proposal_departament_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título da Submissão')),
                ('abstract', models.TextField(verbose_name='Resumo')),
                ('keywords', models.CharField(max_length=255, verbose_name='Palavras-chave')),
                ('justification', models.TextField(verbose_name='Justificativa')),
                ('methodology', models.TextField(verbose_name='Metodologia')),
                ('project_timeline', models.TextField(verbose_name='Cronograma do Projeto')),
                ('project_budget', models.TextField(verbose_name='Orçamento do Projeto')),
                ('expected_results', models.TextField(verbose_name='Resultados Esperados')),
                ('status', models.CharField(max_length=50, verbose_name='Status da Submissão')),
                ('version', models.IntegerField(default=1, verbose_name='Versão da Submissão')),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Arquivo da Submissão')),
                ('evaluation_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='evaluations.evaluation', verbose_name='Avaliação')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_list', to='proposals.proposal')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_researcher', to='pesquisador.researcher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RectifySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título da Retificação')),
                ('abstract', models.TextField(verbose_name='Resumo')),
                ('keywords', models.CharField(max_length=255, verbose_name='Palavras-chave')),
                ('justification', models.TextField(verbose_name='Justificativa')),
                ('methodology', models.TextField(verbose_name='Metodologia')),
                ('project_timeline', models.TextField(verbose_name='Cronograma do Projeto')),
                ('project_budget', models.TextField(verbose_name='Orçamento do Projeto')),
                ('expected_results', models.TextField(verbose_name='Resultados Esperados')),
                ('status', models.CharField(max_length=50, verbose_name='Status da Retificação')),
                ('rectify_file', models.FileField(blank=True, null=True, upload_to='submissions/rectifications/', verbose_name='Arquivo da Retificação')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectifications_list', to='submission.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
