# Generated by Django 5.2.7 on 2026-02-02 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_researcher', to='user.profile'),
        ),
        migrations.AddField(
            model_name='version',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectifications_list', to='submission.submission'),
        ),
    ]
