# Generated by Django 5.2.7 on 2026-01-20 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_rename_rectifysubmission_version'),
        ('user', '0002_remove_profile_city_remove_profile_neighborhood_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='rectify_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='evaluation_score',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='expected_results',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='justification',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='methodology',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='project_budget',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='project_timeline',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='version',
        ),
        migrations.RemoveField(
            model_name='version',
            name='status',
        ),
        migrations.AlterField(
            model_name='submission',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions_researcher', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título da Retificação'),
        ),
    ]
