# Generated by Django 5.2.7 on 2026-02-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('in_evaluation', 'Em Avaliação'), ('approved', 'Aprovado'), ('rejected', 'Reprovado')], default='in_evaluation', max_length=50, verbose_name='Status da Submissão'),
        ),
    ]
