# Generated by Django 5.2.7 on 2026-02-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attachments',
            field=models.FileField(blank=True, help_text='Anexos complementares à submissão', null=True, upload_to='submissions/attachments', verbose_name='Anexos (opcional)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, help_text='Faça upload do arquivo PDF principal da submissão', null=True, upload_to='submissions/', verbose_name='Arquivo Principal da Submissão'),
        ),
    ]
