# Generated by Django 5.2.7 on 2026-01-14 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisador', '0001_initial'),
        ('submission', '0002_rename_rectifysubmission_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions_researcher', to='pesquisador.researcher', verbose_name='Pesquisador'),
        ),
    ]
