# Generated by Django 5.2.7 on 2026-01-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Arquivo do Projeto'),
        ),
    ]
